<?php
session_start();
include_once('../../includes/config.php');
include_once('../../includes/functions.php');

$cnfNetworking = array_diff(scandir(RASPI_CONFIG_NETWORKING, 1),array('..','.'));
$cnfNetworking = array_combine($cnfNetworking,$cnfNetworking);
$IFC = array();
$strConfFile = "";

foreach($cnfNetworking as $index=>$file) 
{
    $used=false;
    if($index != "defaults") 
    {
        $cnfFile = parse_ini_file(RASPI_CONFIG_NETWORKING.'/'.$file);

        if (isset($cnfFile['static']))
        {
            $IFC[$file]["ssid"] = "";
            $IFC[$file]["psk"] = "";
            if( $cnfFile['ifaceoff'] === 'true')
            {
                $IFC[$file]["iface"] = $cnfFile['interface'];
            }
            else if( $cnfFile['static'] === 'true')
            {
                $IFC[$file]["iface"] = $cnfFile['interface'];
                $IFC[$file]["addr"] = $cnfFile['ip_address'];
                $IFC[$file]["gateway"] = $cnfFile['routers'];
                $IFC[$file]["dns"] = $cnfFile['domain_name_server'];
                $IFC[$file]["nmask"] = $cnfFile['net_mask'];
				if(isset( $cnfFile['ssid']))
	                $IFC[$file]["ssid"] = $cnfFile['ssid'];
				if(isset( $cnfFile['psk']))
	                	$IFC[$file]["psk"] = $cnfFile['psk'];

                $strConfFile .= "interface ".$cnfFile['interface']."\n";
                $strConfFile .= "static ip_address=".$cnfFile['ip_address']."\n";
                $strConfFile .= "static routers=".$cnfFile['routers']."\n";
                $strConfFile .= "static domain_name_servers=".$cnfFile['domain_name_server']."\n";
            }
            elseif($cnfFile['static'] === 'false')
            {

                $IFC[$file]["iface"] = $cnfFile['interface'];
                $IFC[$file]["addr"] = "dhcp";
                $IFC[$file]["gateway"] = $cnfFile['routers'];
                $IFC[$file]["dns"] = $cnfFile['domain_name_server'];
                $IFC[$file]["nmask"] = $cnfFile['net_mask'];

				if(isset( $cnfFile['ssid']))
	                $IFC[$file]["ssid"] = $cnfFile['ssid'];
				if(isset( $cnfFile['psk']))
                	$IFC[$file]["psk"] = $cnfFile['psk'];

                $strConfFile .= "profile static_".$cnfFile['interface']."\n";
                $strConfFile .= "static ip_address=".$cnfFile['ip_address']."\n";
                $strConfFile .= "static routers=".$cnfFile['routers']."\n";
                $strConfFile .= "static domain_name_servers=".$cnfFile['domain_name_server']."\n\n";
                $strConfFile .= "interface ".$cnfFile['interface']."\n";
                $strConfFile .= "fallback static_".$cnfFile['interface']."\n\n";
            }
            else
            {
                $strConfFile .= "#DHCP configured for ".$cnfFile['interface']."\n\n";
            }
        }
    } 
    if (!isset($cnfFile['static']))
    {
        $strConfFile .= file_get_contents(RASPI_CONFIG_NETWORKING.'/'.$index)."\n\n";
    }
}

// gen ifconfig
$FIC = (RASPI_CONFIG_NETWORKING.'/interfaces');
$now = time();



file_put_contents($FIC, "# generated by odrisyan time server {$now}\n");
file_put_contents($FIC, "auto lo\n",FILE_APPEND);
file_put_contents($FIC, "iface lo inet loopback\n\n",FILE_APPEND);
//echo "<pre>";
//var_dump($IFC);

foreach($IFC as $key=>$VAL)
{
    $KEY=str_replace(".ini","",$key);

    if($VAL["addr"]=="dhcp")
    {
        file_put_contents($FIC,"auto ". $KEY."\n",FILE_APPEND);
        file_put_contents($FIC,"    allow-hotplug ".$KEY."\n",FILE_APPEND);
        file_put_contents($FIC,"    iface ".$KEY." inet dhcp\n\n",FILE_APPEND);
    }
    else if($VAL["addr"]=="static")
    {
        file_put_contents($FIC,"auto ". $KEY."\n",FILE_APPEND);
        file_put_contents($FIC,"    allow-hotplug ".$KEY."\n",FILE_APPEND);
        file_put_contents($FIC,"    iface " . $KEY . " inet static\n",FILE_APPEND);
        file_put_contents($FIC,"    address " . $VAL['addr'] . "\n",FILE_APPEND);
        file_put_contents($FIC,"    netmask " . $VAL['nmask'] . "\n",FILE_APPEND);
        file_put_contents($FIC,"    gateway " . $VAL['gateway'] . "\n",FILE_APPEND);
		if(strlen($VAL['ssid'])>1 && $KEY=="wlan0")
		{
        	file_put_contents($FIC,"        wpa-ssid " . $VAL['ssid'] . "\n",FILE_APPEND);
        	file_put_contents($FIC,"        wpa-psk " . $VAL['psk'] . "\n",FILE_APPEND);
		}
        file_put_contents($FIC,"    #nameserver " . $VAL['dns'] . "\n\n",FILE_APPEND);
    }
    else
    {
        file_put_contents($FIC,"######## auto ". $KEY."\n",FILE_APPEND);
        file_put_contents($FIC,"    iface " . $KEY . " inet manual\n\n",FILE_APPEND);
        sysyem("sudo ifconfig ".$KEY. " down");
    }
}

$FIC = (RASPI_CONFIG_NETWORKING.'/resolv.conf');
file_put_contents($FIC, "nameserver " . $VAL['dns'] . "\n");


if (is_file(RASPI_CONFIG_NETWORKING."/interfaces"))
{
	if(!is_file(RASPI_CONFIG_NETWORKING."/interfaces_old"))
	{
		system("cp /etc/network/interfaces ".RASPI_CONFIG_NETWORKING."/interfaces_old");
	}
	if(!is_file(RASPI_CONFIG_NETWORKING."/resolv.conf_old"))
	{
		system("cp /etc/resolv.conf ".RASPI_CONFIG_NETWORKING."/resolv.conf_old");
	}
    $ret = shell_exec("sudo cp -vf ".RASPI_CONFIG_NETWORKING."/resolv.conf  /etc/resolv.conf ");
    $ret .= shell_exec("sudo cp -vf ".RASPI_CONFIG_NETWORKING."/interfaces  /etc/network/interfaces ");


    $ret .= shell_exec("sudo /etc/init.d/networking restart");

	$has = shell_exec("grep {$now} /etc/network/interfaces grep -v grep");
	if(!empty($has))
	{
		$output = ['return'=>0,'output'=>'Settings successfully applied'];
		echo json_encode($output);
	}
	else
	{
		$output = ['return'=>1,'output'=>'{$ret}'];
		echo json_encode($output);
	}
}



?>
