#!/bin/bash
# Copyright (C) M<7iv5
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### BEGIN INIT INFO
# Provides:          autostart
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

PATHH=/home/marius/.run

stop() {
    for file in $(ls -v $PATHH); do
       if [[ $file =~ "sh" ]];then
                echo "killing $file" >> $INSTALLF
                killall $file
                sleep .2
       fi
    done
}

start() {
    for file in $(ls -v $PATHH); do
       if [[ $file =~ "sh" ]];then
        if [[ $file =~ ".bash" ]];then
                   echo "starting $file in background" >> $INSTALLF
                   $PATHH/$file > /dev/null &
        else
                   echo "starting $file in foreground" >> $INSTALLF
                   $PATHH/$file > /dev/null
        fi
       fi
    done
}

case "$1" in
start)
    stop
    start
    ;;
stop)
    stop
    ;;
retart)
    stop
    start
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
esac

